[workspace]
members = [
    "struct-fields",
    "actix-web-extract",
    "hyper-multipart",

    "hi-jira2",
    "hi-push",

    "example"
]

[profile.release]
lto = true

[profile.release.package.hi-push]
opt-level = 'z'
