[package]
name = "agora-rtm"
version = "0.1.3"
edition = "2021"
description = "Agora Rtm SDK ffi bindings"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

[build-dependencies]
bindgen = "0.60.1"