[package]
name = "struct-fields"
version = "0.0.2"
edition = "2021"
description = "common"
license = "MIT"
repository = "https://github.com/hikit-io/hikit-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affix = "0.1.2"